### ISSUE TITLE
Friendship Step Farming

### ISSUE THREAD

**Issue by TeamZ3N** [DrMaple/IronMONPatchEditor#1]
Is there a way to automatically increase friendship on starting Pokemon to max for evolutions? You can take an unlimited walk in the lab before the first fight. This seems similar to the always spawn items in safe areas, no advantage but time saving.

**Comment by DrMaple** [comment]
I've added an NPC in my [Faster Fire Red](https://github.com/DrMaple/Faster-Fire-Red) patch that allows you to gain a large amount of friendship with limitations. You can read more about it on its page.
