### ISSUE TITLE
Emerald doesn't seem to work correctly?

### ISSUE THREAD

**Issue by wildtorterra** [DrMaple/IronMONPatchEditor#2]
My settings:
Instant Pokemon Center -- Instant Healing
Speech Skip -- Skip
Gender -- Female
Player name -- TRISTAN
The program hasn't given me any errors and seems to recognize this as the QoL patch

What happens:
The intro is skipped straight to the back of the truck, but I'm a male character (not the Female character I chose). I get out of the truck, and it spawns me in Petalburg in the house directly south from the gym. In my trainer card, my name reads "TRISTANSAFA" with the ID number 65467 (this stays consistent between resets). And the player sprite fails to load correctly when battle starts.

The non-important stuff, but I wanted to share this anyway because I thought it would be funny:
Just for fun, I tried to see how far I can get with the game in this state. I do the catching tutorial, and after all that finishes and I talk to Norman again, he simply states "You are already free." Not sure if that's supposed to happen, but I move on. I buy Pokeballs, and catch a Pokemon so I have something in my party. I make my way through Route 102, and in the pond at the beginning of the Route is one of the Hot Spring ladies from Lavaridge Town just chilling there. The Footprints guy in Oldale quotes Bilbo from Lord of the Rings for some reason and it was at this point that I lost any sense of reality. The mart guy is in front of the Pokemart, and when I talk to him, he takes me into the forest and wonders why I'd follow a stranger. In Littleroot, there's a truck parked in front of the both of the houses and both moms, the little brother, and Vigoroth are all hanging out at both houses at the same time. This whole experience just feels like one bizarre fever dream. From here, I'm softlocked because I haven't talked to the Rival in their house, nor will the game let me. 

Anyway -- If I can be of any further help, I can be best reached on Discord at Wild Torterra#3692

**Comment by DrMaple** [comment]
Resolved when this was posted, forgot to close the issue.
