### ISSUE TITLE
Unhandled Exception when Player / Rival name contains a space character

### ISSUE THREAD

**Issue by Fellshadow** [DrMaple/IronMONPatchEditor#3]
When there is a space character present in either of the player/rival names the program returns an unhandled exception when attempting to save the ROM. The base games allow you to put spaces in the character names so some people would attempt to do the same with the patch editor.

Attached error below, from a brief look it seems like the space character isn't present in the character mappings dictionaries?
![image](https://github.com/DrMaple/IronMONPatchEditor/assets/106463662/197b6f36-347d-4fc8-84cf-c1f2f939fb8f)

**Comment by DrMaple** [comment]
[Fixed](https://github.com/DrMaple/IronMONPatchEditor/releases/tag/1.1), thanks for the report.
